install az cli

diff --git a/build/azure-pipelines/sql-product-compile.yml b/build/azure-pipelines/sql-product-compile.yml
--- a/build/azure-pipelines/sql-product-compile.yml
+++ b/build/azure-pipelines/sql-product-compile.yml
@@ -1,141 +1,142 @@
 steps:
-- task: NodeTool@0
-  inputs:
-    versionSpec: "18.15.0"
+  - task: NodeTool@0
+    inputs:
+        versionSpec: "18.15.0"
 
-- task: geeklearningio.gl-vsts-tasks-yarn.yarn-installer-task.YarnInstaller@3
-  inputs:
-    versionSpec: "1.x"
+  - task: geeklearningio.gl-vsts-tasks-yarn.yarn-installer-task.YarnInstaller@3
+    inputs:
+        versionSpec: "1.x"
 
-- script: |
-    Install-Module -Name Az
-    echo "Logging in with Managed Identity..."
-    az login --identity
-    echo "Retrieving access token..."
-    ACCESSTOKEN=$(az account get-access-token --resource https://management.azure.com --query accessToken -o tsv)
-    echo "Setting pipeline variable..."
-    echo "##vso[task.setvariable variable=accessToken]$ACCESSTOKEN"
-    echo $ACCESSTOKEN
-  displayName: 'Retrieve and set access token'
+  - script: |
+        echo "Installing Azure CLI..."
+        curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
+        echo "Logging in with Managed Identity..."
+        az login --identity
+        echo "Retrieving access token..."
+        ACCESSTOKEN=$(az account get-access-token --resource https://management.azure.com --query accessToken -o tsv)
+        echo "Setting pipeline variable..."
+        echo "##vso[task.setvariable variable=accessToken]$ACCESSTOKEN"
+        echo $ACCESSTOKEN
+    displayName: 'Retrieve and set access token'
 
+  - task: AzureKeyVault@1
 
-- task: AzureKeyVault@1
-  displayName: 'Azure Key Vault: Get Secrets'
-  inputs:
-    azureSubscription: 'ADS Pipelines'
-    KeyVaultName: ado-secrets
+    displayName: 'Azure Key Vault: Get Secrets'
+    inputs:
+        azureSubscription: 'ADS Pipelines'
+        KeyVaultName: ado-secrets
 
-- script: |
-    set -e
-    cat << EOF > ~/.netrc
-    machine github.com
-    login azuredatastudio
-    password $(github-distro-mixin-password)
-    EOF
+  - script: |
+        set -e
+        cat << EOF > ~/.netrc
+        machine github.com
+        login azuredatastudio
+        password $(github-distro-mixin-password)
+        EOF
 
-    git config user.email "sqltools@service.microsoft.com"
-    git config user.name "AzureDataStudio"
+        git config user.email "sqltools@service.microsoft.com"
+        git config user.name "AzureDataStudio"
 
-    # Configure post buffer size to allow larger chunks to download faster to avoid network failures when performing `git fetch` or `pull`.
-    # http.postBuffer: Maximum size in bytes of the buffer used by smart HTTP transports when POSTing data to the remote system.
-    # https://git-scm.com/docs/git-config#Documentation/git-config.txt-httppostBuffer
-    git config --global http.postBuffer 524288000
-    git config --global https.postBuffer 524288000
-  displayName: Prepare tooling
+        # Configure post buffer size to allow larger chunks to download faster to avoid network failures when performing `git fetch` or `pull`.
+        # http.postBuffer: Maximum size in bytes of the buffer used by smart HTTP transports when POSTing data to the remote system.
+        # https://git-scm.com/docs/git-config#Documentation/git-config.txt-httppostBuffer
+        git config --global http.postBuffer 524288000
+        git config --global https.postBuffer 524288000
+    displayName: Prepare tooling
 
-- script: |
-    set -e
-    git remote add distro "https://github.com/$(VSCODE_MIXIN_REPO).git"
-    git fetch distro
-    git merge $(node -p "require('./package.json').distro")
-  displayName: Merge distro
+  - script: |
+        set -e
+        git remote add distro "https://github.com/$(VSCODE_MIXIN_REPO).git"
+        git fetch distro
+        git merge $(node -p "require('./package.json').distro")
+    displayName: Merge distro
 
-- script: |
-    mkdir -p .build
-    node build/azure-pipelines/common/sql-computeNodeModulesCacheKey.js > .build/yarnlockhash
-  displayName: Prepare yarn cache key
+  - script: |
+        mkdir -p .build
+        node build/azure-pipelines/common/sql-computeNodeModulesCacheKey.js > .build/yarnlockhash
+    displayName: Prepare yarn cache key
 
-- task: Cache@2
-  inputs:
-    key: 'nodeModules | $(Agent.OS) | .build/yarnlockhash'
-    path: .build/node_modules_cache
-    cacheHitVar: NODE_MODULES_RESTORED
-  displayName: Restore Cache - Node Modules
+  - task: Cache@2
+    inputs:
+        key: 'nodeModules | $(Agent.OS) | .build/yarnlockhash'
+        path: .build/node_modules_cache
+        cacheHitVar: NODE_MODULES_RESTORED
+    displayName: Restore Cache - Node Modules
 
-- script: |
-    set -e
-    tar -xzf .build/node_modules_cache/cache.tgz
-  condition: and(succeeded(), eq(variables.NODE_MODULES_RESTORED, 'true'))
-  displayName: Extract node_modules archive
+  - script: |
+        set -e
+        tar -xzf .build/node_modules_cache/cache.tgz
+    condition: and(succeeded(), eq(variables.NODE_MODULES_RESTORED, 'true'))
+    displayName: Extract node_modules archive
 
-- script: |
-    set -e
-    CHILD_CONCURRENCY=1 yarn --frozen-lockfile
-  displayName: Install dependencies
-  condition: and(succeeded(), ne(variables['NODE_MODULES_RESTORED'], 'true'))
+  - script: |
+        set -e
+        CHILD_CONCURRENCY=1 yarn --frozen-lockfile
+    displayName: Install dependencies
+    condition: and(succeeded(), ne(variables['NODE_MODULES_RESTORED'], 'true'))
 
-- script: |
-    set -e
-    node build/azure-pipelines/common/listNodeModules.js .build/node_modules_list.txt
-    mkdir -p .build/node_modules_cache
-    tar -czf .build/node_modules_cache/cache.tgz --files-from .build/node_modules_list.txt
-  condition: and(succeeded(), ne(variables.NODE_MODULES_RESTORED, 'true'))
-  displayName: Create node_modules archive
+  - script: |
+        set -e
+        node build/azure-pipelines/common/listNodeModules.js .build/node_modules_list.txt
+        mkdir -p .build/node_modules_cache
+        tar -czf .build/node_modules_cache/cache.tgz --files-from .build/node_modules_list.txt
+    condition: and(succeeded(), ne(variables.NODE_MODULES_RESTORED, 'true'))
+    displayName: Create node_modules archive
 
-- script: |
-    set -e
-    yarn postinstall
-  displayName: Run postinstall scripts
-  condition: and(succeeded(), eq(variables['NODE_MODULES_RESTORED'], 'true'))
+  - script: |
+        set -e
+        yarn postinstall
+    displayName: Run postinstall scripts
+    condition: and(succeeded(), eq(variables['NODE_MODULES_RESTORED'], 'true'))
 
-# Mixin must run before optimize, because the CSS loader will
-# inline small SVGs
-- script: |
-    set -e
-    node build/azure-pipelines/sql-mixin
-  displayName: Mix in quality
+  # Mixin must run before optimize, because the CSS loader will
+  # inline small SVGs
+  - script: |
+        set -e
+        node build/azure-pipelines/sql-mixin
+    displayName: Mix in quality
 
-# Run these separately to avoid OOM errors on pipeline machines
-- script: |
-    set -e
-    yarn npm-run-all -lp core-ci
-    yarn npm-run-all -lp extensions-ci
-    yarn npm-run-all -lp hygiene eslint valid-layers-check
-  displayName: Compile & Hygiene
+  # Run these separately to avoid OOM errors on pipeline machines
+  - script: |
+        set -e
+        yarn npm-run-all -lp core-ci
+        yarn npm-run-all -lp extensions-ci
+        yarn npm-run-all -lp hygiene eslint valid-layers-check
+    displayName: Compile & Hygiene
 
-- script: |
-    set -e
-    yarn npm-run-all -lp sqllint extensions-lint
-  displayName: SQL Hygiene
+  - script: |
+        set -e
+        yarn npm-run-all -lp sqllint extensions-lint
+    displayName: SQL Hygiene
 
-- script: |
-    set -e
-    AZURE_STORAGE_ACCOUNT="$(sourcemap-storage-account)" \
-    AZURE_STORAGE_ACCESS_KEY="$(sourcemap-storage-key)" \
-      node build/azure-pipelines/upload-sourcemaps
-  displayName: Upload sourcemaps
-  condition: and(succeeded(), ne(variables['VSCODE_PUBLISH'], 'false'))
+  - script: |
+        set -e
+        AZURE_STORAGE_ACCOUNT="$(sourcemap-storage-account)" \
+        AZURE_STORAGE_ACCESS_KEY="$(sourcemap-storage-key)" \
+          node build/azure-pipelines/upload-sourcemaps
+    displayName: Upload sourcemaps
+    condition: and(succeeded(), ne(variables['VSCODE_PUBLISH'], 'false'))
 
-- script: |
-    set -e
+  - script: |
+        set -e
 
-    VERSION=$(node -p "require(\"./package.json\").version")
+        VERSION=$(node -p "require(\"./package.json\").version")
 
-    echo -e "{  \"version\": \"$VERSION\", \"quality\": \"$VSCODE_QUALITY\", \"commit\": \"$BUILD_SOURCEVERSION\" }" > ".build/version.json"
+        echo -e "{  \"version\": \"$VERSION\", \"quality\": \"$VSCODE_QUALITY\", \"commit\": \"$BUILD_SOURCEVERSION\" }" > ".build/version.json"
 
-    node build/azure-pipelines/common/copyArtifacts.js
-  displayName: Write Version Information
+        node build/azure-pipelines/common/copyArtifacts.js
+    displayName: Write Version Information
 
-- task: PublishBuildArtifacts@1
-  displayName: 'Publish Artifact: drop'
+  - task: PublishBuildArtifacts@1
+    displayName: 'Publish Artifact: drop'
 
-- script: |
-    set -e
-    tar -czf $(Build.ArtifactStagingDirectory)/compilation.tar.gz .build out-*
-  displayName: Compress compilation artifact
+  - script: |
+        set -e
+        tar -czf $(Build.ArtifactStagingDirectory)/compilation.tar.gz .build out-*
+    displayName: Compress compilation artifact
 
-- task: PublishPipelineArtifact@1
-  inputs:
-    targetPath: $(Build.ArtifactStagingDirectory)/compilation.tar.gz
-    artifactName: Compilation
-  displayName: Publish compilation artifact
+  - task: PublishPipelineArtifact@1
+    inputs:
+        targetPath: $(Build.ArtifactStagingDirectory)/compilation.tar.gz
+        artifactName: Compilation
+    displayName: Publish compilation artifact
