added better update-localization yml file

diff --git a/build/azure-pipelines/update-localization.yml b/build/azure-pipelines/update-localization.yml
--- a/build/azure-pipelines/update-localization.yml
+++ b/build/azure-pipelines/update-localization.yml
@@ -1,311 +1,127 @@
-pr:
-  branches:
-    include: ["main"]
+steps:
+  - task: NodeTool@0
+    inputs:
+      versionSpec: "12.18.3"
 
-schedules:
-  - cron: "0 5 * * Mon-Fri"
-    displayName: Mon-Fri at 7:00
-    branches:
-      include: ["main"]
+  - task: geeklearningio.gl-vsts-tasks-yarn.yarn-installer-task.YarnInstaller@2
+    inputs:
+      versionSpec: "1.x"
 
-parameters:
-  - name: VSCODE_QUALITY
-    displayName: Quality
-    type: string
-    default: insider
-    values:
-      - exploration
-      - insider
-      - stable
-  - name: ENABLE_TERRAPIN
-    displayName: "Enable Terrapin"
-    type: boolean
-    default: true
-  - name: VSCODE_BUILD_WIN32
-    displayName: "🎯 Windows x64"
-    type: boolean
-    default: true
-  - name: VSCODE_BUILD_WIN32_32BIT
-    displayName: "🎯 Windows ia32"
-    type: boolean
-    default: true
-  - name: VSCODE_BUILD_WIN32_ARM64
-    displayName: "🎯 Windows arm64"
-    type: boolean
-    default: true
-  - name: VSCODE_BUILD_LINUX
-    displayName: "🎯 Linux x64"
-    type: boolean
-    default: true
-  - name: VSCODE_BUILD_LINUX_ARM64
-    displayName: "🎯 Linux arm64"
-    type: boolean
-    default: true
-  - name: VSCODE_BUILD_LINUX_ARMHF
-    displayName: "🎯 Linux armhf"
-    type: boolean
-    default: true
-  - name: VSCODE_BUILD_LINUX_ALPINE
-    displayName: "🎯 Alpine Linux"
-    type: boolean
-    default: true
-  - name: VSCODE_BUILD_MACOS
-    displayName: "🎯 macOS x64"
-    type: boolean
-    default: true
-  - name: VSCODE_BUILD_MACOS_ARM64
-    displayName: "🎯 macOS arm64"
-    type: boolean
-    default: true
-  - name: VSCODE_BUILD_MACOS_UNIVERSAL
-    displayName: "🎯 macOS universal"
-    type: boolean
-    default: true
-  - name: VSCODE_BUILD_WEB
-    displayName: "🎯 Web"
-    type: boolean
-    default: true
-  - name: VSCODE_PUBLISH
-    displayName: "Publish to builds.code.visualstudio.com"
-    type: boolean
-    default: true
-  - name: VSCODE_RELEASE
-    displayName: "Release build if successful"
-    type: boolean
-    default: false
-  - name: VSCODE_COMPILE_ONLY
-    displayName: "Run Compile stage exclusively"
-    type: boolean
-    default: false
-  - name: VSCODE_STEP_ON_IT
-    displayName: "Skip tests"
-    type: boolean
-    default: false
+  - task: AzureKeyVault@1
+    displayName: "Azure Key Vault: Get Secrets"
+    inputs:
+      azureSubscription: "vscode-builds-subscription"
+      KeyVaultName: vscode
 
-variables:
-  - name: ENABLE_TERRAPIN
-    value: ${{ eq(parameters.ENABLE_TERRAPIN, true) }}
-  - name: VSCODE_QUALITY
-    value: ${{ parameters.VSCODE_QUALITY }}
-  - name: VSCODE_BUILD_STAGE_WINDOWS
-    value: ${{ or(eq(parameters.VSCODE_BUILD_WIN32, true), eq(parameters.VSCODE_BUILD_WIN32_32BIT, true), eq(parameters.VSCODE_BUILD_WIN32_ARM64, true)) }}
-  - name: VSCODE_BUILD_STAGE_LINUX
-    value: ${{ or(eq(parameters.VSCODE_BUILD_LINUX, true), eq(parameters.VSCODE_BUILD_LINUX_ARMHF, true), eq(parameters.VSCODE_BUILD_LINUX_ARM64, true), eq(parameters.VSCODE_BUILD_LINUX_ALPINE, true), eq(parameters.VSCODE_BUILD_WEB, true)) }}
-  - name: VSCODE_BUILD_STAGE_MACOS
-    value: ${{ or(eq(parameters.VSCODE_BUILD_MACOS, true), eq(parameters.VSCODE_BUILD_MACOS_ARM64, true)) }}
-  - name: VSCODE_CIBUILD
-    value: ${{ in(variables['Build.Reason'], 'IndividualCI', 'BatchedCI') }}
-  - name: VSCODE_PUBLISH
-    value: ${{ and(eq(parameters.VSCODE_PUBLISH, true), eq(variables.VSCODE_CIBUILD, false)) }}
-  - name: VSCODE_SCHEDULEDBUILD
-    value: ${{ eq(variables['Build.Reason'], 'Schedule') }}
-  - name: VSCODE_STEP_ON_IT
-    value: ${{ eq(parameters.VSCODE_STEP_ON_IT, true) }}
-  - name: VSCODE_BUILD_MACOS_UNIVERSAL
-    value: ${{ and(eq(variables['VSCODE_PUBLISH'], true), eq(parameters.VSCODE_BUILD_MACOS, true), eq(parameters.VSCODE_BUILD_MACOS_ARM64, true), eq(parameters.VSCODE_BUILD_MACOS_UNIVERSAL, true)) }}
+  - script: |
+      set -e
+      cat << EOF > ~/.netrc
+      machine github.com
+      login vscode
+      password $(github-distro-mixin-password)
+      EOF
 
-resources:
-  containers:
-    - container: vscode-x64
-      image: vscodehub.azurecr.io/vscode-linux-build-agent:bionic-x64
-      endpoint: VSCodeHub
-      options: --user 0:0
-    - container: vscode-arm64
-      image: vscodehub.azurecr.io/vscode-linux-build-agent:stretch-arm64
-      endpoint: VSCodeHub
-    - container: vscode-armhf
-      image: vscodehub.azurecr.io/vscode-linux-build-agent:stretch-armhf
-      endpoint: VSCodeHub
-    - container: snapcraft
-      image: snapcore/snapcraft:stable
+      git config user.email "vscode@microsoft.com"
+      git config user.name "VSCode"
+    displayName: Prepare tooling
 
-stages:
-  - stage: Compile
-    jobs:
-      - job: Compile
-        pool: compile
-        variables:
-          VSCODE_ARCH: x64
-        steps:
-          - template: product-compile.yml
+  - script: |
+      set -e
+      git pull --no-rebase https://github.com/$(VSCODE_MIXIN_REPO).git $(node -p "require('./package.json').distro")
+    displayName: Merge distro
 
-  - ${{ if and(eq(parameters.VSCODE_COMPILE_ONLY, false), eq(variables['VSCODE_BUILD_STAGE_WINDOWS'], true)) }}:
-    - stage: Windows
-      dependsOn:
-        - Compile
-      pool:
-        vmImage: VS2017-Win2016
-      jobs:
+  - script: |
+      npx https://aka.ms/enablesecurefeed standAlone
+    displayName: Switch to Terrapin packages
+    timeoutInMinutes: 5
+    condition: and(succeeded(), eq(variables['ENABLE_TERRAPIN'], 'true'))
 
-        - ${{ if eq(parameters.VSCODE_BUILD_WIN32, true) }}:
-          - job: Windows
-            timeoutInMinutes: 90
-            variables:
-              VSCODE_ARCH: x64
-            steps:
-              - template: win32/product-build-win32.yml
+  - script: |
+      mkdir -p .build
+      echo -n $(VSCODE_ARCH) > .build/arch
+      echo -n $ENABLE_TERRAPIN > .build/terrapin
+    displayName: Prepare yarn cache flags
 
-        - ${{ if and(eq(variables['VSCODE_CIBUILD'], false), eq(parameters.VSCODE_BUILD_WIN32_32BIT, true)) }}:
-          - job: Windows32
-            timeoutInMinutes: 90
-            variables:
-              VSCODE_ARCH: ia32
-            steps:
-              - template: win32/product-build-win32.yml
+  - task: 1ESLighthouseEng.PipelineArtifactCaching.RestoreCacheV1.RestoreCache@1
+    inputs:
+      keyfile: ".build/arch, .build/terrapin, build/.cachesalt, .yarnrc, remote/.yarnrc, **/yarn.lock, !**/node_modules/**/yarn.lock, !**/.*/**/yarn.lock"
+      targetfolder: "**/node_modules, !**/node_modules/**/node_modules"
+      vstsFeed: "npm-vscode"
 
-        - ${{ if and(eq(variables['VSCODE_CIBUILD'], false), eq(parameters.VSCODE_BUILD_WIN32_ARM64, true)) }}:
-          - job: WindowsARM64
-            timeoutInMinutes: 90
-            variables:
-              VSCODE_ARCH: arm64
-            steps:
-              - template: win32/product-build-win32.yml
+  - script: |
+      set -e
+      export npm_config_arch=$(NPM_ARCH)
 
-  - ${{ if and(eq(parameters.VSCODE_COMPILE_ONLY, false), eq(variables['VSCODE_BUILD_STAGE_LINUX'], true)) }}:
-    - stage: Linux
-      dependsOn:
-        - Compile
-      pool:
-        vmImage: "Ubuntu-18.04"
-      jobs:
+      if [ -z "$CC" ] || [ -z "$CXX" ]; then
+        export CC=$(which gcc-5)
+        export CXX=$(which g++-5)
+      fi
 
-        - ${{ if eq(parameters.VSCODE_BUILD_LINUX, true) }}:
-          - job: Linux
-            container: vscode-x64
-            variables:
-              VSCODE_ARCH: x64
-              NPM_ARCH: x64
-            steps:
-              - template: linux/product-build-linux.yml
+      if [ "$VSCODE_ARCH" == "x64" ]; then
+        export VSCODE_REMOTE_CC=$(which gcc-4.8)
+        export VSCODE_REMOTE_CXX=$(which g++-4.8)
+        export VSCODE_REMOTE_NODE_GYP=$(which node-gyp)
+      fi
 
-        - ${{ if and(eq(variables['VSCODE_CIBUILD'], false), eq(parameters.VSCODE_BUILD_LINUX, true)) }}:
-          - job: LinuxSnap
-            dependsOn:
-              - Linux
-            container: snapcraft
-            variables:
-              VSCODE_ARCH: x64
-            steps:
-              - template: linux/snap-build-linux.yml
+      for i in {1..3}; do # try 3 times, for Terrapin
+        yarn --frozen-lockfile && break
+        if [ $i -eq 3 ]; then
+          echo "Yarn failed too many times" >&2
+          exit 1
+        fi
+        echo "Yarn failed $i, trying again..."
+      done
+    env:
+      ELECTRON_SKIP_BINARY_DOWNLOAD: 1
+      PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 1
+    displayName: Install dependencies
+    condition: and(succeeded(), ne(variables['CacheRestored'], 'true'))
 
-        - ${{ if and(eq(variables['VSCODE_CIBUILD'], false), eq(parameters.VSCODE_BUILD_LINUX_ARMHF, true)) }}:
-          - job: LinuxArmhf
-            container: vscode-armhf
-            variables:
-              VSCODE_ARCH: armhf
-              NPM_ARCH: armv7l
-            steps:
-              - template: linux/product-build-linux.yml
+  - task: 1ESLighthouseEng.PipelineArtifactCaching.SaveCacheV1.SaveCache@1
+    inputs:
+      keyfile: ".build/arch, .build/terrapin, build/.cachesalt, .yarnrc, remote/.yarnrc, **/yarn.lock, !**/node_modules/**/yarn.lock, !**/.*/**/yarn.lock"
+      targetfolder: "**/node_modules, !**/node_modules/**/node_modules"
+      vstsFeed: "npm-vscode"
+    condition: and(succeeded(), ne(variables['CacheRestored'], 'true'))
 
-        # TODO@joaomoreno: We don't ship ARM snaps for now
-        - ${{ if and(false, eq(variables['VSCODE_CIBUILD'], false), eq(parameters.VSCODE_BUILD_LINUX_ARMHF, true)) }}:
-          - job: LinuxSnapArmhf
-            dependsOn:
-              - LinuxArmhf
-            container: snapcraft
-            variables:
-              VSCODE_ARCH: armhf
-            steps:
-              - template: linux/snap-build-linux.yml
+  # Mixin must run before optimize, because the CSS loader will inline small SVGs
+  - script: |
+      set -e
+      node build/azure-pipelines/mixin
+    displayName: Mix in quality
 
-        - ${{ if and(eq(variables['VSCODE_CIBUILD'], false), eq(parameters.VSCODE_BUILD_LINUX_ARM64, true)) }}:
-          - job: LinuxArm64
-            container: vscode-arm64
-            variables:
-              VSCODE_ARCH: arm64
-              NPM_ARCH: arm64
-            steps:
-              - template: linux/product-build-linux.yml
+  - script: |
+      set -e
+      yarn gulp compile-build
+      yarn gulp compile-extensions-build
+      yarn gulp minify-vscode
+      yarn gulp vscode-reh-linux-x64-min
+      yarn gulp vscode-reh-web-linux-x64-min
+    displayName: Compile
 
-        # TODO@joaomoreno: We don't ship ARM snaps for now
-        - ${{ if and(false, eq(variables['VSCODE_CIBUILD'], false), eq(parameters.VSCODE_BUILD_LINUX_ARM64, true)) }}:
-          - job: LinuxSnapArm64
-            dependsOn:
-              - LinuxArm64
-            container: snapcraft
-            variables:
-              VSCODE_ARCH: arm64
-            steps:
-              - template: linux/snap-build-linux.yml
+  - script: |
+      set -e
+      AZURE_STORAGE_ACCESS_KEY="$(ticino-storage-key)" \
+        node build/azure-pipelines/upload-sourcemaps
+    displayName: Upload sourcemaps
+    condition: and(succeeded(), ne(variables['VSCODE_PUBLISH'], 'false'))
 
-        - ${{ if and(eq(variables['VSCODE_CIBUILD'], false), eq(parameters.VSCODE_BUILD_LINUX_ALPINE, true)) }}:
-          - job: LinuxAlpine
-            steps:
-              - template: linux/product-build-alpine.yml
+  - script: |
+      set -e
+      VERSION=`node -p "require(\"./package.json\").version"`
+      AZURE_DOCUMENTDB_MASTERKEY="$(builds-docdb-key-readwrite)" \
+        node build/azure-pipelines/common/createBuild.js $VERSION
+    displayName: Create build
+    condition: and(succeeded(), ne(variables['VSCODE_PUBLISH'], 'false'))
 
-        - ${{ if and(eq(variables['VSCODE_CIBUILD'], false), eq(parameters.VSCODE_BUILD_WEB, true)) }}:
-          - job: LinuxWeb
-            variables:
-              VSCODE_ARCH: x64
-            steps:
-              - template: web/product-build-web.yml
+  # we gotta tarball everything in order to preserve file permissions
+  - script: |
+      set -e
+      tar -czf $(Build.ArtifactStagingDirectory)/compilation.tar.gz .build out-*
+    displayName: Compress compilation artifact
 
-  - ${{ if and(eq(parameters.VSCODE_COMPILE_ONLY, false), eq(variables['VSCODE_BUILD_STAGE_MACOS'], true)) }}:
-    - stage: macOS
-      dependsOn:
-        - Compile
-      pool:
-        vmImage: macOS-latest
-      jobs:
-
-        - ${{ if eq(parameters.VSCODE_BUILD_MACOS, true) }}:
-          - job: macOS
-            timeoutInMinutes: 90
-            variables:
-              VSCODE_ARCH: x64
-            steps:
-              - template: darwin/product-build-darwin.yml
-
-        - ${{ if and(eq(variables['VSCODE_CIBUILD'], false), eq(parameters.VSCODE_BUILD_MACOS_ARM64, true)) }}:
-          - job: macOSARM64
-            timeoutInMinutes: 90
-            variables:
-              VSCODE_ARCH: arm64
-            steps:
-              - template: darwin/product-build-darwin.yml
-
-        - ${{ if eq(variables['VSCODE_BUILD_MACOS_UNIVERSAL'], true) }}:
-          - job: macOSUniversal
-            dependsOn:
-              - macOS
-              - macOSARM64
-            timeoutInMinutes: 90
-            variables:
-              VSCODE_ARCH: universal
-            steps:
-              - template: darwin/product-build-darwin.yml
-
-  - ${{ if and(eq(variables['VSCODE_PUBLISH'], true), eq(parameters.VSCODE_COMPILE_ONLY, false)) }}:
-    - stage: Mooncake
-      dependsOn:
-        - ${{ if eq(variables['VSCODE_BUILD_STAGE_WINDOWS'], true) }}:
-          - Windows
-        - ${{ if eq(variables['VSCODE_BUILD_STAGE_LINUX'], true) }}:
-          - Linux
-        - ${{ if eq(variables['VSCODE_BUILD_STAGE_MACOS'], true) }}:
-          - macOS
-      condition: succeededOrFailed()
-      pool:
-        vmImage: "Ubuntu-18.04"
-      jobs:
-        - job: SyncMooncake
-          displayName: Sync Mooncake
-          steps:
-            - template: sync-mooncake.yml
-
-  - ${{ if and(eq(parameters.VSCODE_COMPILE_ONLY, false), or(eq(parameters.VSCODE_RELEASE, true), and(in(parameters.VSCODE_QUALITY, 'insider', 'exploration'), eq(variables['VSCODE_SCHEDULEDBUILD'], true)))) }}:
-    - stage: Release
-      dependsOn:
-        - ${{ if eq(variables['VSCODE_BUILD_STAGE_WINDOWS'], true) }}:
-          - Windows
-        - ${{ if eq(variables['VSCODE_BUILD_STAGE_LINUX'], true) }}:
-          - Linux
-        - ${{ if eq(variables['VSCODE_BUILD_STAGE_MACOS'], true) }}:
-          - macOS
-      pool:
-        vmImage: "Ubuntu-18.04"
-      jobs:
-        - job: ReleaseBuild
-          displayName: Release Build
-          steps:
-            - template: release.yml
+  - task: PublishPipelineArtifact@1
+    inputs:
+      targetPath: $(Build.ArtifactStagingDirectory)/compilation.tar.gz
+      artifactName: Compilation
+    displayName: Publish compilation artifact
